export const menuArray = [
  {
    id: 1,
    category: "Pizza",
    name: "ДЕРЕВЕНСКАЯ",
    description: "САЛЯМИ",
    price: 480,
    imageUrl: "https://your-cdn.com/images/ham-mushrooms.jpg",
  },
  {
    id: 2,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/rustic.jpg",
  },
  {
    id: 3,
    category: "Pizza",
    name: "КОРНИШОНЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bbq.jpg",
  },
  {
    id: 4,
    category: "Pizza",
    name: "ЛУК КРАСНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/pepperoni.jpg",
  },
  {
    id: 5,
    category: "Pizza",
    name: "КУРИЦА КОПЧЁНАЯ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salami.jpg",
  },
  {
    id: 6,
    category: "Pizza",
    name: "ПЕПЕРОННИ",
    description: "МОЦАРЕЛЛА",
    price: 500,
    imageUrl: "https://your-cdn.com/images/mozzarella.jpg",
  },
  {
    id: 7,
    category: "Pizza",
    name: "ПОМИДОРЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/pickles.jpg",
  },
  {
    id: 8,
    category: "Pizza",
    name: "САЛЯМИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/red-onion.jpg",
  },
  {
    id: 9,
    category: "Pizza",
    name: "ВЕТЧИНА-ГРИБЫ",
    description: "ВЕТЧИНА",
    price: 450,
    imageUrl: "https://your-cdn.com/images/smoked-chicken.jpg",
  },
  {
    id: 10,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/mushrooms.jpg",
  },
  {
    id: 11,
    category: "Pizza",
    name: "ШАМПИНЬОНЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tomatoes.jpg",
  },
  {
    id: 12,
    category: "Pizza",
    name: "БАРБЕКЮ",
    description: "ОХОТНИЧЬИ КОЛБАСКИ",
    price: 520,
    imageUrl: "https://your-cdn.com/images/hunters-sausages.jpg",
  },
  {
    id: 13,
    category: "Pizza",
    name: "СОУС БАРБЕКЮ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bbq-sauce.jpg",
  },
  {
    id: 14,
    category: "Pizza",
    name: "КОРНИШОНЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bacon.jpg",
  },
  {
    id: 15,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/400-grams.jpg",
  },
  {
    id: 16,
    category: "Pizza",
    name: "САЛЯМИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/carbonara.jpg",
  },
  {
    id: 17,
    category: "Pizza",
    name: "БЕКОН",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/marinara.jpg",
  },
  {
    id: 18,
    category: "Pizza",
    name: "4 МЯСА",
    description: "КУРИЦА КОПЧЁНАЯ",
    price: 550,
    imageUrl: "https://your-cdn.com/images/four-meats.jpg",
  },
  {
    id: 19,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/hawaiian.jpg",
  },
  {
    id: 20,
    category: "Pizza",
    name: "ВЕТЧИНА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/four-cheeses.jpg",
  },
  {
    id: 21,
    category: "Pizza",
    name: "САЛЯМИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/caesar.jpg",
  },
  {
    id: 22,
    category: "Pizza",
    name: "БЕКОН",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bacon.jpg",
  },
  {
    id: 23,
    category: "Pizza",
    name: "КАРБОНАРА",
    description: "БЕКОН",
    price: 525,
    imageUrl: "https://your-cdn.com/images/ham.jpg",
  },
  {
    id: 24,
    category: "Pizza",
    name: "ВЕТЧИНА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/mozzarella.jpg",
  },
  {
    id: 25,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/mushrooms.jpg",
  },
  {
    id: 26,
    category: "Pizza",
    name: "ШАМПИНЬОНЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/pineapple.jpg",
  },
  {
    id: 27,
    category: "Pizza",
    name: "МАРИНАРА",
    description: "МОРСКОЙ КОКТЕЙЛЬ",
    price: 600,
    imageUrl: "https://your-cdn.com/images/smoked-chicken.jpg",
  },
  {
    id: 28,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salami.jpg",
  },
  {
    id: 29,
    category: "Pizza",
    name: "ОЛИВКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/seafood-cocktail.jpg",
  },
  {
    id: 30,
    category: "Pizza",
    name: "ЦЕЗАРЬ",
    description: "КОПЧЁНАЯ КУРИЦА",
    price: 550,
    imageUrl: "https://your-cdn.com/images/olives.jpg",
  },
  {
    id: 31,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp-roll.jpg",
  },
  {
    id: 32,
    category: "Pizza",
    name: "ЛИСТЬЯ САЛАТА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese-roll.jpg",
  },
  {
    id: 33,
    category: "Pizza",
    name: "ПОМИДОР",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salmon-roll.jpg",
  },
  {
    id: 34,
    category: "Pizza",
    name: "СОУС ЦЕЗАРЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-roll.jpg",
  },
  {
    id: 35,
    category: "Pizza",
    name: "СРЕДИЗЕМНОМОРСКИЕ ТРАВЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-lava.jpg",
  },
  {
    id: 36,
    category: "Pizza",
    name: "ГАВАЙСКАЯ",
    description: "АНАНАС",
    price: 500,
    imageUrl: "https://your-cdn.com/images/salmon-tempura.jpg",
  },
  {
    id: 37,
    category: "Pizza",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel-tempura.jpg",
  },
  {
    id: 38,
    category: "Pizza",
    name: "КОПЧЁНАЯ КУРИЦА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese-tempura.jpg",
  },
  {
    id: 39,
    category: "Pizza",
    name: "4 СЫРА",
    description: "СЫР МОЦАРЕЛЛА",
    price: 550,
    imageUrl: "https://your-cdn.com/images/tempura-volcano.jpg",
  },
  {
    id: 40,
    category: "Pizza",
    name: "СЫР МААСДАМ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-mix.jpg",
  },
  {
    id: 41,
    category: "Pizza",
    name: "СЫР ДОР БЛЮ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-chicken-hot.jpg",
  },
  {
    id: 42,
    category: "Pizza",
    name: "СЫР ЧЕДДЕР",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-cheese-hot.jpg",
  },
  {
    id: 43,
    category: "Rolls",
    name: "ТЕМПУРА ЛАВА",
    description: "КРЕВЕТКА",
    price: 400,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 44,
    category: "Rolls",
    name: "КРЕМ СЫР",
    description: "",
    price: 320,
    imageUrl: "https://your-cdn.com/images/crab.jpg",
  },
  {
    id: 45,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: 380,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 46,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: 340,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 47,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 48,
    category: "Rolls",
    name: "ТЕМПУРА ВУЛКАН 🌶️",
    description: "КРЕВЕТКА",
    price: 500,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 49,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: 450,
    imageUrl: "https://your-cdn.com/images/tempura-ebi-hot.jpg",
  },
  {
    id: 50,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: 550,
    imageUrl: "https://your-cdn.com/images/tempura-unagi.jpg",
  },
  {
    id: 51,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/gentle-tempura.jpg",
  },
  {
    id: 52,
    category: "Rolls",
    name: "ТЕМПУРА МИКС",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 420,
    imageUrl: "https://your-cdn.com/images/sliced-cheese.jpg",
  },
  {
    id: 53,
    category: "Rolls",
    name: "СЫР СЛАЙСОВЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salmon.jpg",
  },
  {
    id: 54,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 55,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/dynamite.jpg",
  },
  {
    id: 56,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/ebi-chirazi.jpg",
  },
  {
    id: 57,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/big-tempura.jpg",
  },
  {
    id: 58,
    category: "Rolls",
    name: "ТЕМПУРА ЧИЗ ХОТ 🌶️",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 250,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 59,
    category: "Rolls",
    name: "СЫР СЛАЙСОВЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/3-sauces.jpg",
  },
  {
    id: 60,
    category: "Rolls",
    name: "СЫР МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 61,
    category: "Rolls",
    name: "ТЕМПУРА ЧИКЕН ХОТ",
    description: "КУРИЦА КОПЧЁНАЯ",
    price: 250,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 62,
    category: "Rolls",
    name: "СЫР СЛАЙСОВЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab.jpg",
  },
  {
    id: 63,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salmon-slices.jpg",
  },
  {
    id: 64,
    category: "Rolls",
    name: "БИГ ТЕМПУРА 🌶️",
    description: "ЛОСОСЬ ЖАРЕНЫЙ",
    price: 400,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 65,
    category: "Rolls",
    name: "3 СОУСА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/green-onion.jpg",
  },
  {
    id: 66,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-cucumber.jpg",
  },
  {
    id: 67,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel-slices.jpg",
  },
  {
    id: 68,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 69,
    category: "Rolls",
    name: "ТЕМПУРА ЭБИ ХОТ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 400,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 70,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 71,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-eel.jpg",
  },
  {
    id: 72,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-onion.jpg",
  },
  {
    id: 73,
    category: "Rolls",
    name: "ТЕМПУРА УНАГИ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 400,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 74,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-salmon.jpg",
  },
  {
    id: 75,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-eel.jpg",
  },
  {
    id: 76,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 77,
    category: "Rolls",
    name: "ТЕМПУРА НЕЖНЫЙ",
    description: "КРЕВЕТКА",
    price: 380,
    imageUrl: "https://your-cdn.com/images/philadelphia.jpg",
  },
  {
    id: 78,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-salmon.jpg",
  },
  {
    id: 79,
    category: "Rolls",
    name: "ЭБИ ЧИРАЗИ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 440,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 80,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-luxe.jpg",
  },
  {
    id: 81,
    category: "Rolls",
    name: "ЗАМЕС ЧИРАЗИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-light.jpg",
  },
  {
    id: 82,
    category: "Rolls",
    name: "ДИНАМИТ 🌶️",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 340,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 83,
    category: "Rolls",
    name: "СЫР СЛАЙСОВЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-mix.jpg",
  },
  {
    id: 84,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 85,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-mix.jpg",
  },
  {
    id: 86,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ",
    description: "ЛОСОСЬ НАРЕЗКА",
    price: 550,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 87,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 88,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С ОГУРЦОМ",
    description: "ЛОСОСЬ НАРЕЗКА",
    price: 550,
    imageUrl: "https://your-cdn.com/images/california-sesame.jpg",
  },
  {
    id: 89,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 90,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 91,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С УГРЁМ",
    description: "УГОРЬ НАРЕЗКА",
    price: 600,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 92,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-luxe.jpg",
  },
  {
    id: 93,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-crab.jpg",
  },
  {
    id: 94,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/canadian.jpg",
  },
  {
    id: 95,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ С ЛУКОМ",
    description: "ЛОСОСЬ НАРЕЗКА",
    price: 550,
    imageUrl: "https://your-cdn.com/images/salmon-chicken.jpg",
  },
  {
    id: 96,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 97,
    category: "Rolls",
    name: "ЛУК ЗЕЛЁНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shiitake-mushrooms.jpg",
  },
  {
    id: 98,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ ЛЮКС",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 580,
    imageUrl: "https://your-cdn.com/images/sliced-eel.jpg",
  },
  {
    id: 99,
    category: "Rolls",
    name: "ЛОСОСЬ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese-mix.jpg",
  },
  {
    id: 100,
    category: "Rolls",
    name: "УГОРЬ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/spicy-roll.jpg",
  },
  {
    id: 101,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 102,
    category: "Rolls",
    name: "ФИЛАДЕЛЬФИЯ ЛАЙТ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 420,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 103,
    category: "Rolls",
    name: "ЛОСОСЬ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cucumber.jpg",
  },
  {
    id: 104,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-shiitake.jpg",
  },
  {
    id: 105,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ С ШИИТАКИ",
    description: "ЛОСОСЬ",
    price: 340,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 106,
    category: "Rolls",
    name: "КУРИЦА",
    description: "",
    price: 300,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 107,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-eel.jpg",
  },
  {
    id: 108,
    category: "Rolls",
    name: "ШИИТАКИ ГРИБЫ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 109,
    category: "Rolls",
    name: "УГОРЬ НАРЕЗКА",
    description: "",
    price: 300,
    imageUrl: "https://your-cdn.com/images/salmon.jpg",
  },
  {
    id: 110,
    category: "Rolls",
    name: "СЫР ЗАМЕС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel-inside.jpg",
  },
  {
    id: 111,
    category: "Rolls",
    name: "КАЛИФОРНИЯ КУНЖУТ",
    description: "КРАБ ЗАМЕС",
    price: 260,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 112,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 113,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 114,
    category: "Rolls",
    name: "КАЛИФОРНИЯ ЛЮКС",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 380,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 115,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/kimchi-maki.jpg",
  },
  {
    id: 116,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/teri-maki.jpg",
  },
  {
    id: 117,
    category: "Rolls",
    name: "КАЛИФОРНИЯ КРАБ",
    description: "ИКРА МАСАГА",
    price: 300,
    imageUrl: "https://your-cdn.com/images/unagi-maki.jpg",
  },
  {
    id: 118,
    category: "Rolls",
    name: "КРАБ ЗАМЕС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 119,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 120,
    category: "Rolls",
    name: "КАНАДСКИЙ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 540,
    imageUrl: "https://your-cdn.com/images/ebi-maki.jpg",
  },
  {
    id: 121,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/yasai-maki.jpg",
  },
  {
    id: 122,
    category: "Rolls",
    name: "УГОРЬ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 123,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 124,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tomato-concasse.jpg",
  },
  {
    id: 125,
    category: "Rolls",
    name: "СПАЙСИ РОЛЛ 🌶️",
    description: "ЛОСОСЬ ЖАРЕНЫЙ",
    price: 300,
    imageUrl: "https://your-cdn.com/images/bell-pepper.jpg",
  },
  {
    id: 126,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/kappa-maki.jpg",
  },
  {
    id: 127,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-cucumbers.jpg",
  },
  {
    id: 128,
    category: "Rolls",
    name: "ТЕРИ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 240,
    imageUrl: "https://your-cdn.com/images/masago-caviar.jpg",
  },
  {
    id: 129,
    category: "Rolls",
    name: "ЛОСОСЬ ЖАРЕНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salmon.jpg",
  },
  {
    id: 130,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tuna-flakes.jpg",
  },
  {
    id: 131,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bonito.jpg",
  },
  {
    id: 132,
    category: "Rolls",
    name: "КИМЧИ МАКИ 🌶️",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 240,
    imageUrl: "https://your-cdn.com/images/geisha.jpg",
  },
  {
    id: 133,
    category: "Rolls",
    name: "ЛОСОСЬ ЖАРЕНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sunrise.jpg",
  },
  {
    id: 134,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/gentleness.jpg",
  },
  {
    id: 135,
    category: "Rolls",
    name: "ЭБИ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 260,
    imageUrl: "https://your-cdn.com/images/crab-mix.jpg",
  },
  {
    id: 136,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 137,
    category: "Rolls",
    name: "УНАГИ МАКИ",
    description: "УГОРЬ ВНУТРИ",
    price: 300,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 138,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 139,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/lava.jpg",
  },
  {
    id: 140,
    category: "Rolls",
    name: "ЯСАЙ МАКИ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 220,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 141,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 142,
    category: "Rolls",
    name: "ТОМАТ КАНКАССЕ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/chicken-maki.jpg",
  },
  {
    id: 143,
    category: "Rolls",
    name: "ПЕРЕЦ БОЛГАРСКИЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-spice.jpg",
  },
  {
    id: 144,
    category: "Rolls",
    name: "КАППА МАКИ",
    description: "КУНЖУТ",
    price: 150,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 145,
    category: "Rolls",
    name: "ОГУРЕЦ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tomato-concasse.jpg",
  },
  {
    id: 146,
    category: "Rolls",
    name: "НЕЖНОСТЬ",
    description: "КРАБ ЗАМЕС",
    price: 400,
    imageUrl: "https://your-cdn.com/images/sake-maki.jpg",
  },
  {
    id: 147,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sliced-cucumber.jpg",
  },
  {
    id: 148,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/salmon.jpg",
  },
  {
    id: 149,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tomatoes-maki.jpg",
  },
  {
    id: 150,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 151,
    category: "Rolls",
    name: "БОНИТО",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 280,
    imageUrl: "https://your-cdn.com/images/cream-cheese-mix.jpg",
  },
  {
    id: 152,
    category: "Rolls",
    name: "ЛОСОСЬ ЖАРЕНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 153,
    category: "Rolls",
    name: "СТРУЖКА ТУНЦА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 154,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 155,
    category: "Rolls",
    name: "Лава",
    description: "ЛОСОСЬ",
    price: 340,
    imageUrl: "https://your-cdn.com/images/crab.jpg",
  },
  {
    id: 156,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: 280,
    imageUrl: "https://your-cdn.com/images/eel.jpg",
  },
  {
    id: 157,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: 500,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 158,
    category: "Rolls",
    name: "КРЕМ СЫР",
    description: "",
    price: 250,
    imageUrl: "https://your-cdn.com/images/cream-cheese-mix.jpg",
  },
  {
    id: 159,
    category: "Rolls",
    name: "ГЕЙША",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 300,
    imageUrl: "https://your-cdn.com/images/sesame.jpg",
  },
  {
    id: 160,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 161,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel.jpg",
  },
  {
    id: 162,
    category: "Rolls",
    name: "ЛОСОСЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 163,
    category: "Rolls",
    name: "ВОСХОД",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 290,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 164,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-spicy.jpg",
  },
  {
    id: 165,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 166,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel.jpg",
  },
  {
    id: 167,
    category: "Rolls",
    name: "СЯКЕ МАКИ",
    description: "ОГУРЕЦ НАРЕЗКА",
    price: 250,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 168,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 169,
    category: "Rolls",
    name: "ИКРА МАСАГА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-volcano.jpg",
  },
  {
    id: 170,
    category: "Rolls",
    name: "ЧИКЕН МАКИ 🌶️",
    description: "КУРИЦА КОПЧЁНАЯ",
    price: 250,
    imageUrl: "https://your-cdn.com/images/fried-salmon.jpg",
  },
  {
    id: 171,
    category: "Rolls",
    name: "ОГУРЕЦ НАРЕЗКА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/shrimp.jpg",
  },
  {
    id: 172,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab.jpg",
  },
  {
    id: 173,
    category: "Rolls",
    name: "СЫР СЛАЙСОВЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/eel.jpg",
  },
  {
    id: 174,
    category: "Rolls",
    name: "КРАБИ СПАЙС 🌶️",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 180,
    imageUrl: "https://your-cdn.com/images/cream-cheese.jpg",
  },
  {
    id: 175,
    category: "Rolls",
    name: "КРАБ ЗАМЕС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream-cheese-mix.jpg",
  },
  {
    id: 176,
    category: "Rolls",
    name: "ТОМАТОС МАКИ",
    description: "СЫР СЛИВОЧНЫЙ",
    price: 150,
    imageUrl: "https://your-cdn.com/images/baked-roll.jpg",
  },
  {
    id: 177,
    category: "Rolls",
    name: "ТОМАТ КАНКАССЕ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/volcano.jpg",
  },
  {
    id: 178,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ ВУЛКАН 🌶️",
    description: "ЛОСОСЬ",
    price: 450,
    imageUrl: "https://your-cdn.com/images/vegetarian-set.jpg",
  },
  {
    id: 179,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: 550,
    imageUrl: "https://your-cdn.com/images/set-hit.jpg",
  },
  {
    id: 180,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: 500,
    imageUrl: "https://your-cdn.com/images/fila-cucumber.jpg",
  },
  {
    id: 181,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-crab.jpg",
  },
  {
    id: 182,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ СПАЙСИ 🌶️",
    description: "ЛОСОСЬ",
    price: 340,
    imageUrl: "https://your-cdn.com/images/canadian-roll.jpg",
  },
  {
    id: 183,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: 380,
    imageUrl: "https://your-cdn.com/images/set-classic.jpg",
  },
  {
    id: 184,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: 280,
    imageUrl: "https://your-cdn.com/images/tomatoes-maki.jpg",
  },
  {
    id: 185,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: 440,
    imageUrl: "https://your-cdn.com/images/kappa-maki.jpg",
  },
  {
    id: 186,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/yasai-maki.jpg",
  },
  {
    id: 187,
    category: "Rolls",
    name: "СЫР ЗАМЕС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/set-elite.jpg",
  },
  {
    id: 188,
    category: "Rolls",
    name: "ЗАПЕЧЁННЫЙ РОЛЛ",
    description: "ЛОСОСЬ",
    price: 340,
    imageUrl: "https://your-cdn.com/images/tobi-cheese.jpg",
  },
  {
    id: 189,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: 380,
    imageUrl: "https://your-cdn.com/images/sunrise.jpg",
  },
  {
    id: 190,
    category: "Rolls",
    name: "КРАБ",
    description: "",
    price: 280,
    imageUrl: "https://your-cdn.com/images/bonito.jpg",
  },
  {
    id: 191,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: 440,
    imageUrl: "https://your-cdn.com/images/classic-fila.jpg",
  },
  {
    id: 192,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/lava-crab.jpg",
  },
  {
    id: 193,
    category: "Rolls",
    name: "СЫР ЗАМЕС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-luxe.jpg",
  },
  {
    id: 194,
    category: "Rolls",
    name: "КУНЖУТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sets.jpg",
  },
  {
    id: 195,
    category: "Rolls",
    name: "ВУЛКАН 🌶️",
    description: "ЛОСОСЬ",
    price: 450,
    imageUrl: "https://your-cdn.com/images/set-waukesha.jpg",
  },
  {
    id: 196,
    category: "Rolls",
    name: "УГОРЬ",
    description: "",
    price: 550,
    imageUrl: "https://your-cdn.com/images/set-hit-hot.jpg",
  },
  {
    id: 197,
    category: "Rolls",
    name: "КРЕВЕТКА",
    description: "",
    price: 500,
    imageUrl: "https://your-cdn.com/images/set-assorti.jpg",
  },
  {
    id: 198,
    category: "Rolls",
    name: "СЫР СЛИВОЧНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-volcano-shrimp.jpg",
  },
  {
    id: 199,
    category: "Sets",
    name: "СЕТ “ХИТ”",
    description: "ТОБИ ЧИЗ",
    price: 900,
    imageUrl: "https://your-cdn.com/images/spicy-salmon.jpg",
  },
  {
    id: 200,
    category: "Sets",
    name: "ВОСХОД",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-cheese-hot.jpg",
  },
  {
    id: 201,
    category: "Sets",
    name: "БОНИТО",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-lava-crab.jpg",
  },
  {
    id: 202,
    category: "Sets",
    name: "НАБОР: 1",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-spicy.jpg",
  },
  {
    id: 203,
    category: "Sets",
    name: "ВЕГЕТЕРИАНСКИЙ",
    description: "ТОМАТОС МАКИ",
    price: 650,
    imageUrl: "https://your-cdn.com/images/lava-salmon.jpg",
  },
  {
    id: 204,
    category: "Sets",
    name: "КАПА МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-fried.jpg",
  },
  {
    id: 205,
    category: "Sets",
    name: "ЯСАЙ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-lava-shrimp.jpg",
  },
  {
    id: 206,
    category: "Sets",
    name: "НАБОР: 1",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-luxe.jpg",
  },
  {
    id: 207,
    category: "Sets",
    name: "СЕТ “ЭЛИТ”",
    description: "ФИЛА КЛАССИЧЕСКАЯ",
    price: 1400,
    imageUrl: "https://your-cdn.com/images/big-tempura.jpg",
  },
  {
    id: 208,
    category: "Sets",
    name: "ЛАВА КРАБ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/dynamite.jpg",
  },
  {
    id: 209,
    category: "Sets",
    name: "КАЛИФОРНИЯ ЛЮКС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-chicken-hot.jpg",
  },
  {
    id: 210,
    category: "Sets",
    name: "НАБОР: 2",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-cheese-hot.jpg",
  },
  {
    id: 211,
    category: "Sets",
    name: "СЕТ “КЛАССИК”",
    description: "ФИЛА С ОГУРЦОМ",
    price: 1500,
    imageUrl: "https://your-cdn.com/images/unagi-tempura.jpg",
  },
  {
    id: 212,
    category: "Sets",
    name: "КАЛИФОРНИЯ КРАБ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/spicy-roll.jpg",
  },
  {
    id: 213,
    category: "Sets",
    name: "КАНАДСКИЙ РОЛЛ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-spice.jpg",
  },
  {
    id: 214,
    category: "Sets",
    name: "НАБОР: 2",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/ebi-maki.jpg",
  },
  {
    id: 215,
    category: "Sets",
    name: "Chicken Hot",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/chicken-hot.jpg",
  },
  {
    id: 216,
    category: "Sets",
    name: "ТЕМПУРА ЖАРЕНЫЙ",
    description: "ТЕМПУРА ЛАВА С КРЕВЕТКОЙ",
    price: 1800,
    imageUrl: "https://your-cdn.com/images/baked-spicy-salmon.jpg",
  },
  {
    id: 217,
    category: "Sets",
    name: "ТЕМПУРА ЛЮКС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-shrimp.jpg",
  },
  {
    id: 218,
    category: "Sets",
    name: "БИГ ТЕМПУРА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-luxe.jpg",
  },
  {
    id: 219,
    category: "Sets",
    name: "ДИНАМИТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/dynamite.jpg",
  },
  {
    id: 220,
    category: "Sets",
    name: "НАБОР: 2",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/set-viktori.jpg",
  },
  {
    id: 221,
    category: "Sets",
    name: "СЕТ “WAUKESHA”",
    description: "КРАБИ СПАЙС",
    price: 690,
    imageUrl: "https://your-cdn.com/images/baked-spicy-shrimp.jpg",
  },
  {
    id: 222,
    category: "Sets",
    name: "ЭБИ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/baked-salmon.jpg",
  },
  {
    id: 223,
    category: "Sets",
    name: "ЧИКЕН ХОТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tempura-ebi-hot.jpg",
  },
  {
    id: 224,
    category: "Sets",
    name: "НАБОР: 1",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/canadian-roll.jpg",
  },
  {
    id: 225,
    category: "Sets",
    name: "СЕТ “ХИТ-ХОТ”",
    description: "ТЕМПУРА ЛАВА С ЛОСОСЕМ",
    price: 1700,
    imageUrl: "https://your-cdn.com/images/spicy-roll.jpg",
  },
  {
    id: 226,
    category: "Sets",
    name: "ТЕМПУРА ЧИКЕН ХОТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/gentleness.jpg",
  },
  {
    id: 227,
    category: "Sets",
    name: "ТЕМПУРА ЧИЗ ХОТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/chicken-maki.jpg",
  },
  {
    id: 228,
    category: "Sets",
    name: "ТЕМПУРА УНАГИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-sesame.jpg",
  },
  {
    id: 229,
    category: "Sets",
    name: "СПАЙСИ РОЛЛ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/fried-baked.jpg",
  },
  {
    id: 230,
    category: "Sets",
    name: "НАБОР: 3",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/california-sesame.jpg",
  },
  {
    id: 231,
    category: "Sets",
    name: "СЕТ “ASSORTI”",
    description: "ЗАПЕЧЁННЫЙ ВУЛКАН С КРЕВЕТКОЙ",
    price: 1950,
    imageUrl: "https://your-cdn.com/images/tomatoes-maki.jpg",
  },
  {
    id: 232,
    category: "Sets",
    name: "ТЕМПУРА ЛАВА КРАБ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/crab-spicy.jpg",
  },
  {
    id: 233,
    category: "Sets",
    name: "ТЕМПУРА ЧИЗ ХОТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/kimchi-maki.jpg",
  },
  {
    id: 234,
    category: "Sets",
    name: "СПАЙСИ С ЛОСОСЕМ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/teri-maki.jpg",
  },
  {
    id: 235,
    category: "Sets",
    name: "КРАБ СПАЙСИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/sake-maki.jpg",
  },
  {
    id: 236,
    category: "Sets",
    name: "ЛАВА ЛОСОСЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/ebi-maki.jpg",
  },
  {
    id: 237,
    category: "Sets",
    name: "НАБОР: 4",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bonito.jpg",
  },
  {
    id: 238,
    category: "Sets",
    name: "ЖАРЕНО-ЗАПЕЧЁННЫЙ",
    description: "ЗАПЕЧЁННЫЙ СПАЙСИ С ЛОСОСЕМ",
    price: 1550,
    imageUrl: "https://your-cdn.com/images/sunrise.jpg",
  },
  {
    id: 239,
    category: "Sets",
    name: "ЗАПЕЧЁННЫЙ С КРЕВЕТКОЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/set-imperial.jpg",
  },
  {
    id: 240,
    category: "Sets",
    name: "ТЕМПУРА ЛЮКС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-luxe.jpg",
  },
  {
    id: 241,
    category: "Sets",
    name: "ДИНАМИТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/classic-philadelphia.jpg",
  },
  {
    id: 242,
    category: "Sets",
    name: "НАБОР: 2",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/philadelphia-eel.jpg",
  },
  {
    id: 243,
    category: "Sets",
    name: "ФИЛАДЕЛЬФИЯ ЛЮКС",
    description: "ФИЛАДЕЛЬФИЯ КЛАССИЧЕСКАЯ",
    price: 1700,
    imageUrl: "https://your-cdn.com/images/philadelphia-light.jpg",
  },
  {
    id: 244,
    category: "Sets",
    name: "ФИЛАДЕЛЬФИЯ С УГРЁМ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/meat-choice.jpg",
  },
  {
    id: 245,
    category: "Sets",
    name: "ФИЛАДЕЛЬФИЯ ЛАЙТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/beef.jpg",
  },
  {
    id: 246,
    category: "Sets",
    name: "НАБОР: 2",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/pork.jpg",
  },
  {
    id: 247,
    category: "Sets",
    name: "СЕТ “VIKTORI”",
    description: "КАЛИФОРНИЯ В КУНЖУТЕ",
    price: 2100,
    imageUrl: "https://your-cdn.com/images/chicken.jpg",
  },
  {
    id: 248,
    category: "Sets",
    name: "ТОМАТОС МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/noodle-choice.jpg",
  },
  {
    id: 249,
    category: "Sets",
    name: "КРАБ СПАЙСИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/red-onion.jpg",
  },
  {
    id: 250,
    category: "Sets",
    name: "КИМЧИ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/string-bean.jpg",
  },
  {
    id: 251,
    category: "Sets",
    name: "ТЕРИ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bell-pepper.jpg",
  },
  {
    id: 252,
    category: "Sets",
    name: "СЯКЕ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/soy-sauce.jpg",
  },
  {
    id: 253,
    category: "Sets",
    name: "ЭБИ МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/teriyaki-sauce.jpg",
  },
  {
    id: 254,
    category: "Sets",
    name: "БОНИТО",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/garlic-ginger.jpg",
  },
  {
    id: 255,
    category: "Sets",
    name: "ВОСХОД",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/wok-teriyaki.jpg",
  },
  {
    id: 256,
    category: "Sets",
    name: "НАБОР: 4",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/spicy-wok.jpg",
  },
  {
    id: 257,
    category: "Sets",
    name: "СЕТ “ИМПЕРИАЛ”",
    description: "ЗАПЕЧЁННЫЙ СПАЙСИ С КРЕВЕТКОЙ",
    price: 2998,
    imageUrl: "https://your-cdn.com/images/carbonara.jpg",
  },
  {
    id: 258,
    category: "Sets",
    name: "ЗАПЕЧЁННЫЙ С ЛОСОСЕМ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/beef.jpg",
  },
  {
    id: 259,
    category: "Sets",
    name: "ТЕМПУРА ЭБИ ХОТ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/pork.jpg",
  },
  {
    id: 260,
    category: "Sets",
    name: "КАНАДСКИЙ РОЛЛ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/chicken.jpg",
  },
  {
    id: 261,
    category: "Sets",
    name: "СПАЙСИ РОЛЛ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/noodle-choice.jpg",
  },
  {
    id: 262,
    category: "Sets",
    name: "НЕЖНОСТЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/boiled-shiitake.jpg",
  },
  {
    id: 263,
    category: "Sets",
    name: "ЧИКЕН МАКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/string-bean.jpg",
  },
  {
    id: 264,
    category: "Sets",
    name: "КАЛИФОРНИЯ В КУНЖУТЕ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/bell-pepper.jpg",
  },
  {
    id: 265,
    category: "Sets",
    name: "НАБОР: 4",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/kimchi-sauce.jpg",
  },
  {
    id: 266,
    category: "WOK",
    name: "КАРБОНАРА",
    description: "ФЕТУЧИНИ ВАРЕНЫЙ",
    price: 450,
    imageUrl: "https://your-cdn.com/images/aroid-sauce.jpg",
  },
  {
    id: 267,
    category: "WOK",
    name: "МОЦАРЕЛЛА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/boiled-fettuccine.jpg",
  },
  {
    id: 268,
    category: "WOK",
    name: "ВЕТЧИНА",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/mozzarella.jpg",
  },
  {
    id: 269,
    category: "WOK",
    name: "СЛИВКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/ham.jpg",
  },
  {
    id: 270,
    category: "WOK",
    name: "ЖЕЛТОК",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cream.jpg",
  },
  {
    id: 271,
    category: "WOK",
    name: "БЕКОН",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/yolk.jpg",
  },
  {
    id: 272,
    category: "WOK",
    name: "ОСТРЫЙ ВОК",
    description: "ГОВЯДИНА",
    price: 400,
    imageUrl: "https://your-cdn.com/images/bacon.jpg",
  },
  {
    id: 273,
    category: "WOK",
    name: "СВИНИНА",
    description: "",
    price: 375,
    imageUrl: "https://your-cdn.com/images/nuggets.jpg",
  },
  {
    id: 274,
    category: "WOK",
    name: "КУРИЦА",
    description: "",
    price: 350,
    imageUrl: "https://your-cdn.com/images/grilled-sausage.jpg",
  },
  {
    id: 275,
    category: "WOK",
    name: "ЛАПША НА ВЫБОР",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/french-fries.jpg",
  },
  {
    id: 276,
    category: "WOK",
    name: "ЛУК КРАСНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/grilled-chicken.jpg",
  },
  {
    id: 277,
    category: "WOK",
    name: "ШИИТАКИ ГРИБЫ ВАРЕНЫЕ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/strips.jpg",
  },
  {
    id: 278,
    category: "WOK",
    name: "ФАСОЛЬ СТРУЧКОВАЯ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/onion-rings.jpg",
  },
  {
    id: 279,
    category: "WOK",
    name: "ПЕРЕЦ БОЛГАРСКИЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cheese-balls.jpg",
  },
  {
    id: 280,
    category: "WOK",
    name: "СОУС КИМЧИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/squid-rings.jpg",
  },
  {
    id: 281,
    category: "WOK",
    name: "СОУС АРОЙД",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/young-potatoes-spices.jpg",
  },
  {
    id: 282,
    category: "WOK",
    name: "ВОК С ТЕРИЯКИ",
    description: "ГОВЯДИНА",
    price: 400,
    imageUrl: "https://your-cdn.com/images/young-potatoes-skin.jpg",
  },
  {
    id: 283,
    category: "WOK",
    name: "СВИНИНА",
    description: "",
    price: 375,
    imageUrl: "https://your-cdn.com/images/wings-beer.jpg",
  },
  {
    id: 284,
    category: "WOK",
    name: "КУРИЦА",
    description: "",
    price: 350,
    imageUrl: "https://your-cdn.com/images/crab.jpg",
  },
  {
    id: 285,
    category: "WOK",
    name: "ЛАПША НА ВЫБОР",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/meat.jpg",
  },
  {
    id: 286,
    category: "WOK",
    name: "ЛУК КРАСНЫЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/hawaiian.jpg",
  },
  {
    id: 287,
    category: "WOK",
    name: "ФАСОЛЬ СТРУЧКОВАЯ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/cheese.jpg",
  },
  {
    id: 288,
    category: "WOK",
    name: "ПЕРЕЦ БОЛГАРСКИЙ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/mushroom.jpg",
  },
  {
    id: 289,
    category: "WOK",
    name: "СОЕВЫЙ СОУС",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/tsarskaya.jpg",
  },
  {
    id: 290,
    category: "WOK",
    name: "СОУС ТЕРИЯКИ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/small.jpg",
  },
  {
    id: 291,
    category: "WOK",
    name: "ЧЕСНОК/ИМБИРЬ",
    description: "",
    price: null,
    imageUrl: "https://your-cdn.com/images/medium.jpg",
  },
  {
    id: 292,
    category: "GRIL HAUS",
    name: "КАРТОФЕЛЬ МОЛОДОЙ В СПЕЦИЯХ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/large.jpg",
  },
  {
    id: 293,
    category: "GRIL HAUS",
    name: "КАРТОФЕЛЬ МОЛОДОЙ В КОЖУРЕ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/shawarma.jpg",
  },
  {
    id: 294,
    category: "GRIL HAUS",
    name: "КАРТОФЕЛЬ ФРИ",
    description: "150гр",
    price: 185,
    imageUrl: "https://your-cdn.com/images/in-lavash.jpg",
  },
  {
    id: 295,
    category: "GRIL HAUS",
    name: "КОЛЬЦА ЛУКОВЫЕ",
    description: "100гр",
    price: 105,
    imageUrl: "https://your-cdn.com/images/mushroom.jpg",
  },
  {
    id: 296,
    category: "GRIL HAUS",
    name: "КОЛЬЦА КАЛЬМАРА",
    description: "60гр",
    price: 150,
    imageUrl: "https://your-cdn.com/images/german.jpg",
  },
  {
    id: 297,
    category: "GRIL HAUS",
    name: "КРЫЛЫШКИ К ПИВУ",
    description: "150гр",
    price: 225,
    imageUrl: "https://your-cdn.com/images/french.jpg",
  },
  {
    id: 298,
    category: "GRIL HAUS",
    name: "КОЛБАСКА ГРИЛЬ",
    description: "75гр",
    price: 95,
    imageUrl: "https://your-cdn.com/images/classic.jpg",
  },
  {
    id: 299,
    category: "GRIL HAUS",
    name: "КУРИЦА ГРИЛЬ",
    description: "1кг",
    price: 650,
    imageUrl: "https://your-cdn.com/images/garlic.jpg",
  },
  {
    id: 300,
    category: "GRIL HAUS",
    name: "СЫРНЫЕ ШАРИКИ",
    description: "200гр",
    price: 200,
    imageUrl: "https://your-cdn.com/images/cheese.jpg",
  },
  {
    id: 301,
    category: "GRIL HAUS",
    name: "НАГГЕТСЫ",
    description: "230гр",
    price: 199,
    imageUrl: "https://your-cdn.com/images/hot-dog.jpg",
  },
  {
    id: 302,
    category: "GRIL HAUS",
    name: "СТРИПСЫ",
    description: "150гр",
    price: 225,
    imageUrl: "https://your-cdn.com/images/pistachio.jpg",
  },
  {
    id: 303,
    category: "Shawarma",
    name: "ЦАРСКАЯ",
    description:
      "ЛАВАШ, МЯСО КУРИЦЫ, КАПУСТА, МОРКОВЬ ПО-КОРЕЙСКИ, КАРТОФЕЛЬ ФРИ, ТОМАТНЫЙ СОУС",
    price: "190/210/240",
    imageUrl: "https://your-cdn.com/images/apple.jpg",
  },
  {
    id: 304,
    category: "Shawarma",
    name: "ГРИБНАЯ",
    description:
      "ЛАВАШ, МЯСО КУРИЦЫ, МАРИНОВАННЫЙ КРЫМСКИЙ ЛУК, ЖАРЕННЫЕ ШАМПИНЬОНЫ, КАРТОФЕЛЬ ФРИ, СВЕЖИЙ ОГУРЕЦ, ГРИБНОЙ СОУС",
    price: "210/230/270",
    imageUrl: "https://your-cdn.com/images/new-york-coconut.jpg",
  },
  {
    id: 305,
    category: "Shawarma",
    name: "СЫРНАЯ",
    description:
      "ЛАВАШ, МЯСО КУРИЦЫ, КАРТОФЕЛЬ ФРИ, КАПУСТА, СЫР, СВЕЖИЙ ОГУРЕЦ, СЫРНЫЙ СОУС",
    price: "210/230/270",
    imageUrl: "https://your-cdn.com/images/cheesecake.jpg",
  },
  {
    id: 306,
    category: "Shawarma",
    name: "ГАВАЙСКАЯ",
    description:
      "ЛАВАШ, МЯСО КУРИЦЫ, КАРТОФЕЛЬ ФРИ, АНАНАС, СЫР, ПЕКИНСКАЯ КАПУСТА, СОУС",
    price: "230/245/270",
    imageUrl: "https://your-cdn.com/images/double-espresso.jpg",
  },
  {
    id: 307,
    category: "Shawarma",
    name: "МЯСНАЯ",
    description:
      "ЛАВАШ, СВИНИНА В ПАНИРОВКЕ, ТОМАТЫ, ОГУРЕЦ, КАРТОФЕЛЬ ФРИ, СЫРНЫЙ СОУС",
    price: "250/310/370",
    imageUrl: "https://your-cdn.com/images/double-americano.jpg",
  },
  {
    id: 308,
    category: "Shawarma",
    name: "КРАБОВАЯ",
    description:
      "ЛАВАШ, КРАБОВОЕ МЯСО, МАРИНОВАННЫЙ ЛУК, ОГУРЕЦ, МОРКОВЬ, КАПУСТА, СОУС/МАЙОНЕЗ И СОЕВЫЙ",
    price: "230/280/320",
    imageUrl: "https://your-cdn.com/images/coffee.jpg",
  },
  {
    id: 309,
    category: "Hot-Dog",
    name: "КЛАССИЧЕСКИЙ",
    description:
      "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, СВЕЖИЙ ОГУРЕЦ, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС",
    price: 165,
    imageUrl: "https://your-cdn.com/images/chocolate.jpg",
  },
  {
    id: 310,
    category: "Hot-Dog",
    name: "ФРАНЦУЗСКИЙ",
    description:
      "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, ТОМАТЫ, СЫР, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС",
    price: 175,
    imageUrl: "https://your-cdn.com/images/coconut.jpg",
  },
  {
    id: 311,
    category: "Hot-Dog",
    name: "НЕМЕЦКИЙ",
    description:
      "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, МАРИНОВАННЫЙ ОГУРЕЦ, МАРИНОВАННЫЙ ЛУК, БЕЛЫЙ СОУС, КРАСНЫЙ СОУС, ДИЖОНСКАЯ ГОРЧИЦА",
    price: 185,
    imageUrl: "https://your-cdn.com/images/espresso.jpg",
  },
  {
    id: 312,
    category: "Hot-Dog",
    name: "ГРИБНОЙ",
    description:
      "БУЛОЧКА, САРДЕЛЬКА-ГРИЛЬ, ГРИБЫ, МАРИНОВАННЫЙ ЛУК, БЕЛЫЙ СОУС",
    price: 200,
    imageUrl: "https://your-cdn.com/images/americano.jpg",
  },
  {
    id: 313,
    category: "Hot-Dog",
    name: "В ЛАВАШЕ",
    description:
      "ЛАВАШ, САРДЕЛЬКА-ГРИЛЬ, КАПУСТА, МОРКОВЬ ПО-КОРЕЙСКИ, СВЕЖИЙ ОГУРЕЦ, ТОМАТЫ, МАРИНОВАННЫЙ ЛУК, СЫР, СОУС",
    price: 220,
    imageUrl: "https://your-cdn.com/images/cappuccino.jpg",
  },
  {
    id: 314,
    category: "Cheesecake",
    name: "ФИСТАШКОВЫЙ",
    description: "",
    price: 100,
    imageUrl: "https://your-cdn.com/images/almond.jpg",
  },
  {
    id: 315,
    category: "Cheesecake",
    name: "ЯБЛОЧНЫЙ",
    description: "",
    price: 140,
    imageUrl: "https://your-cdn.com/images/salted-caramel.jpg",
  },
  {
    id: 316,
    category: "Cheesecake",
    name: "НЬЮ-ЙОРК КОКОС",
    description: "",
    price: 100,
    imageUrl: "https://your-cdn.com/images/vanilla.jpg",
  },
  {
    id: 317,
    category: "American",
    name: "ДВОЙНОЙ ЭСПРЕССО",
    description: "",
    price: 150,
    imageUrl: "https://your-cdn.com/images/whole-bean-coffee.jpg",
  },
  {
    id: 318,
    category: "American",
    name: "ДВОЙНОЙ АМЕРИКАНО",
    description: "",
    price: 140,
    imageUrl: "https://your-cdn.com/images/syrups.jpg",
  },
  {
    id: 319,
    category: "American",
    name: "ЭСПРЕССО",
    description: "30 мл",
    price: 130,
    imageUrl: "https://your-cdn.com/images/latte.jpg",
  },
  {
    id: 320,
    category: "American",
    name: "АМЕРИКАНО",
    description: "",
    price: 120,
    imageUrl: "https://your-cdn.com/images/milk.jpg",
  },
  {
    id: 321,
    category: "American",
    name: "КАПУЧИНО",
    description: "",
    price: 140,
    imageUrl: "https://your-cdn.com/images/25ml.jpg",
  },
  {
    id: 322,
    category: "American",
    name: "ЛАТТЕ",
    description: "",
    price: 140,
    imageUrl: "https://your-cdn.com/images/15ml.jpg",
  },
  {
    id: 323,
    category: "American",
    name: "МОЛОКО",
    description: "20 мл",
    price: 25,
    imageUrl: "https://your-cdn.com/images/20ml.jpg",
  },
  {
    id: 324,
    category: "American",
    name: "СИРОПЫ",
    description: "СОЛЁНАЯ КАРАМЕЛЬ, МИНДАЛЬ, ВАНИЛЬ, ШОКОЛАД, КОКОС",
    price: 25,
    imageUrl: "https://your-cdn.com/images/30ml.jpg",
  },
];
